name: Build and Copy GoMobile

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21' 

    - name: Install Android SDK
      uses: android-actions/setup-android@v2
      with:
        sdk-version: '30' 

    - name: Install Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25b

    - name: Install GoMobile
      run: go install golang.org/x/mobile/cmd/gomobile@latest

    - name: Build GoMobile app
      run: |
        cd go
        go get golang.org/x/mobile/bind
        gomobile bind -target=android -o ../build/libs

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add app/libs/mylibrary.aar
        git commit -m "Add compiled library"
      
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
